2110336-2565-2/sec2-group11-trainder-frontend

.gitignore
package.json
src/pages/account/login.tsx
src/pages/account/profile.tsx
src/services/auth-header.ts
src/services/auth.service.ts
src/services/user.service.ts
yarn.lock

- Makes the login page authenticate using backend api
- Profile page as one of the page using protected routes

Implements login process via API

---

src/pages/account/login.tsx
src/pages/account/signup.tsx
src/services/auth.service.ts
src/services/user.service.ts

- Update some type for login process
- Implement registration interaction with API
- There might be some need to refactor. This should be handled by the frontend team

implement sign up functions via backend api

---

src/pages/user/home.tsx

- Add link to booking in home page

Booking link in home page

---

src/services/trainer.service.ts
src/services/user.service.ts

- Implement updateTrainerProfile
- Implement filterTrainer
- Implement getTrainerProfile
- Implement updateProfile

feat: Create functions for trainer API

---

src/components/layout.tsx
src/pages/_app.tsx
src/pages/account/profile.tsx
src/pages/user/booking/index.tsx
src/pages/user/booking/profile.tsx
src/pages/user/chat.tsx
src/pages/user/home.tsx
src/pages/user/notification.tsx

- add layout for whole app
- delete navbar from each page

Fix not re-rendering navbar

---

src/pages/account/info.tsx
src/pages/user/booking/index.tsx
src/services/trainer.service.ts

- Fix typo of `specialty`
- Set the filterTrainer in trainer.service to handle the response properly
- Handle the api interaction in filter trainer page
- Still need a **LOT** of CSS fix according to #26, which should be handle by @Ponrawoot separately from this PR.

Filter trainer page interaction with api

---

src/components/navbar.tsx
src/pages/account/info.tsx
src/pages/user/booking/index.tsx

- responsive trainer filter page
- fix navbar position
- change tag a to tag Link in trainer profile page

Fix responsive trainer filter page

---

src/pages/account/info.tsx
src/pages/user/booking/trainer/[username].tsx

- responsive trainer profile page
- edit style of trainer info page

fix: responsive trainer profile page

---

src/components/map.tsx

Get this fking useless feature out asap. This shit cost too much, it's like getting rob.

Remove direction

---

src/components/dropdown.tsx
src/components/navbar.tsx
src/pages/account/info.tsx
src/pages/account/signup.tsx

- create dropdown component
- fixed navbar position

Dropdown component

---

src/components/calendar.tsx

icon-hotfix

---

src/components/backbutton.tsx
src/components/button.tsx
src/components/inputBox.tsx
src/pages/account/info.tsx
src/pages/account/login.tsx
src/pages/account/profile.tsx
src/pages/account/signup.tsx
src/pages/user/booking/index.tsx
src/pages/user/booking/trainer/[username].tsx

- button
- back button
- input box

many components

---

src/pages/account/signup.tsx
yarn.lock

- add link to login page
- add confirm password box
- disable "create account" button when field(s) empty, but form onChange still not detect dropdown boxes (might fix later if I can)

Confirm password box in sign up page

---

.eslintrc.json
src/pages/account/info.tsx
src/pages/account/login.tsx
src/pages/account/profile.tsx
src/pages/user/booking/trainer/[username].tsx
src/pages/user/review/[username].tsx

- eslint is configured wrong.
- change `next/babel` to `next`
- there will be many more warning about missing dependency and many optimization guidance so if you see any of those you **should** try to fix them.

enforce the usage of next linter

---

src/pages/user/home.tsx

- homepage have two button that doesn't appear at the same time
- add loading to wait until data ready then show the page

fix: homepage loading status

---

src/components/navbar.tsx

- `useEffect` to fix hydration error when refreshing a page with navbar

fix: navbar hydration error

---

src/pages/user/booking/[username]/calendar.tsx
src/pages/user/booking/[username]/index.tsx
src/pages/user/booking/complete.tsx
src/services/booking.service.ts

- add booking API
- remove "calendar" and "start chat" button if login as "Trainer"
- add booking complete page

Trainee booking with API

---

src/pages/user/notification.tsx
src/services/booking.service.ts

The notification page now displays upcoming bookings.
Remaining work: Sorting by Date?, Button Behavior.

Notification page

---

src/pages/user/booking/[username]/calendar.tsx
src/pages/user/notification.tsx

- change date in notification page to UTC
- fixed month in notification page
- fixed end time that is sent to API

fix: fixed booking date time

---

src/pages/user/review/[username].tsx

refactor: review modal

---

src/pages/user/notification.tsx
src/services/booking.service.ts

- change update booking to conform with api

add complete booking button

---

src/components/chat/chatbox.tsx
src/components/chat/sidebar.tsx
src/pages/user/chat.tsx
src/services/chat.service.ts
src/utils/date.ts

- just get data for sidebar and past messages
- TODO: websocket to send chat message

API for chat sidebar and past messages

---

src/components/chat/chatbox.tsx
src/components/chat/sidebar.tsx
src/pages/user/booking/[username]/index.tsx
src/pages/user/chat.tsx
src/services/auth.service.ts
src/services/chat.service.ts
src/services/user.service.ts
src/utils/date.ts

connect websocket

---

src/components/common/navbar.tsx
src/pages/account/login.tsx
src/pages/user/home.tsx
src/pages/user/manage_payment/index.tsx
src/pages/user/payment/manage.tsx
src/services/auth.service.ts
src/services/payment.service.ts

create web page for admin
- remove notification and chat in navbar
- edit home menu
- create payment management page
- redirect to home page after login

Actions for admin

---

src/pages/account/info.tsx

- can update fee
- remove rating, trainee count in update info page

editable fee

---

package.json
src/components/chat/chatbox.tsx
src/components/chat/sidebar.tsx
src/components/common/modal.tsx
src/pages/account/info.tsx
src/pages/account/profile.tsx
src/pages/user/booking/[username]/index.tsx
src/pages/user/booking/index.tsx
src/pages/user/chat.tsx
src/pages/user/review/[username].tsx
src/pages/user/review/index.tsx
src/services/chat.service.ts
src/services/trainer.service.ts
src/services/user.service.ts

profile image
